"""add_rejection_fields_to_bom_impact

Revision ID: 1b08d75a6bc0
Revises: b1c76e3be5e8
Create Date: 2025-12-10 14:08:06.531597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b08d75a6bc0'
down_revision: Union[str, None] = 'b1c76e3be5e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bom_impact_results', sa.Column('rejected', sa.Boolean(), nullable=True))
    op.add_column('bom_impact_results', sa.Column('rejected_by_id', sa.Integer(), nullable=True))
    op.add_column('bom_impact_results', sa.Column('rejected_at', sa.DateTime(), nullable=True))
    op.add_column('bom_impact_results', sa.Column('rejection_reason', sa.Text(), nullable=True))
    op.create_index(op.f('ix_bom_impact_results_rejected'), 'bom_impact_results', ['rejected'], unique=False)
    op.create_foreign_key(None, 'bom_impact_results', 'users', ['rejected_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bom_impact_results', type_='foreignkey')
    op.drop_index(op.f('ix_bom_impact_results_rejected'), table_name='bom_impact_results')
    op.drop_column('bom_impact_results', 'rejection_reason')
    op.drop_column('bom_impact_results', 'rejected_at')
    op.drop_column('bom_impact_results', 'rejected_by_id')
    op.drop_column('bom_impact_results', 'rejected')
    # ### end Alembic commands ###
